### ISSUE TITLE
Create cpp-linter-hooks for pre-commit

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-hooks#1]
Add following config to `.pre-commit-config.yaml`
```yaml
repos:
  - repo: https://github.com/shenxianpeng/cpp-linter-hooks
    rev: v0.1.0
    hooks:
      - id: clang-format
        args: [--style=.clang-format]
      - id: clang-tidy
        args: [--checks=.clang-tidy]
```
