### ISSUE TITLE
Enhance this hooks performance with large codebase

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-hooks#62]
Tested with the following config for https://github.com/ggml-org/llama.cpp, it takes much longer than expected. 

Need to try to find a way to enhance performance.

```yaml
- repo: https://github.com/cpp-linter/cpp-linter-hooks
  rev: v0.6.1
  hooks:
  -   id: clang-format
      args: [--style=file, --version=16]  # to load .clang-format
  -   id: clang-tidy
      args: [--checks=.clang-tidy, --version=16] # path/to/.clang-tidy
```

Note to myself: It would be better to try other similar tools' performance; maybe it is not only for cpp-linter-hooks.

________________________________________________________
Executed in   18.21 mins    fish           external
   usr time   30.43 mins  302.00 micros   30.43 mins
   sys time    0.28 mins  483.00 micros    0.28 mins
